apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: servicenow-fetch-template
  title: ServiceNow Fetch Template
  description: Fetch incidents from ServiceNow
  tags:
    - servicenow
    - fetch
spec:
  owner: "manwendra-hotmail"
  type: service
  parameters:
  - title: Provide table name information
    required:
     - tableName
    properties:
      tableName:
        title: Table Name
        type: string
        default: 'incident'
        description: Name of the ServiceNow table to fetch records from (e.g., `incident`)
  steps:
  - id: fetch
    name: Fetch Incident Tickets
    action: servicenow:now:table:retrieveRecords
    input:
      tableName: ${{ parameters.tableName }}

  - id: serialize
    name: Serialize Tickets
    action: roadiehq:utils:serialize:json
    input:
      data:
        tickets: '${{ steps.fetch.output.result }}'

  - id: write
    name: Write to File
    action: roadiehq:utils:fs:write
    input:
      path: ./data.json
      content: ${{ steps.serialize.output.serialized }}

  - id: transform
    name: Transform to Text
    action: roadiehq:utils:jsonata:json:transform
    input:
      path: ${{ steps['write'].output.path }}
      expression: >
        $map($, function($ticket) {
          {
            "line": concat(
              "INC Number: ", $ticket.number, "\n",
              "Description: ", $ticket.short_description, "\n",
              "State: ", $ticket.incident_state, "\n",
              "Priority: ", $ticket.priority, "\n",
              "Opened By: ", $ticket.opened_by.display_value, "\n",
              "------------------------\n"
            )
          }
        })

  output:
    text:
      - title: Incidents
        content: |
          {{#each steps.transform.output.result}}
          {{ this.line }}
          {{/each}}
