apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-now
spec:
  type: service
  lifecycle: production
  owner: "manwendra-hotmail"
  system: service-now
  providesApis:
    - service-now-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: service-now
  tags:
    - servicenow
    - demo
spec:
  owner: "manwendra-hotmail"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-now-api
  description: "servicenow"
spec:
  type: openapi
  lifecycle: production
  owner: "manwendra-hotmail"
  system: service-now
  definition:
    $text: ./openapi.yaml
---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: service-now-template
  title: ServiceNow Template
  description: Fetch incidents from servicenow
  tags:
    - servicenow
spec:
  owner: "manwendra-hotmail"
  type: service
  parameters:
  - title: Provide some simple information
    required:
     - tableName
    properties:
      tableName:
        title: Table Name
        type: string
        description: Unique name of the component
        ui:field: EntityNamePicker
  steps:
  - id: fetch
    name: Template Fetch Ticket Skeleton
    action: servicenow:now:table:retrieveRecords
    input:
      #url: https://ibmksademo1.service-now.com/
      tableName: ${{ parameters.tableName }}
  output:
    text:
      - content: ${{ steps.fetch.result }}
