apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-now
spec:
  type: service
  lifecycle: production
  owner: "manwendra-hotmail"
  system: retail-store
  providesApis:
    - service-now-api
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: service-now
  tags:
    - servicenow
    - demo
spec:
  owner: "manwendra-hotmail"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-now-api
  description: "servicenow"
spec:
  type: openapi
  lifecycle: production
  owner: "manwendra-hotmail"
  system: retail-store
  definition:
    $text: ./openapi.yaml
