apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: service-now
spec:
  type: service
  lifecycle: production
  owner: "manwendra-hotmail"
  system: service-now
  providesApis:
    - service-now-api
  tags:
    - itsm-SNOW
    - ocp-snow-integration
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: service-now
  tags:
    - servicenow
    - demo
spec:
  owner: "manwendra-hotmail"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: service-now-api
  description: "servicenow"
spec:
  type: openapi
  lifecycle: production
  owner: "manwendra-hotmail"
  system: service-now
  definition:
    $text: ./openapi.yaml



---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: servicenow-create-template
  title: ServiceNow Create Template
  description: Create incidents within ServiceNow
  tags:
    - servicenow
    - create
spec:
  owner: "manwendra-hotmail"
  type: service
  parameters:
  - title: Provide mandatory details
    required:
     - tableName
     - shortDescription
    properties:
      tableName:
        title: Table Name
        type: string
        default: 'incident'
        description: Name of the table in ServiceNow (e.g., `incident`)
      shortDescription:
        title: Short Description
        type: string
        description: Summary of the record being created
  steps:
  - id: create
    name: Create Incident in ServiceNow
    action: servicenow:now:table:createRecord
    input:
      tableName: ${{ parameters.tableName }}
      requestBody:
        short_description: ${{ parameters.shortDescription }}
  output:
    ticketUrl: https://ibmksademo1.service-now.com/nav_to.do?uri=${{ parameters.tableName }}.do?sys_id=${{ steps.create.output.sys_id }}
    result: ${{ steps.create.output }}

---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: servicenow-modify-template
  title: ServiceNow Modify Template
  description: Modify details of an existing ticket in ServiceNow
  tags:
    - servicenow
    - modify
spec:
  owner: "manwendra-hotmail"
  type: service
  parameters:
  - title: Provide details to modify
    required:
     - tableName
     - sysId
     - shortDescription
    properties:
      tableName:
        title: Table Name
        type: string
        default: 'incident'
        description: Name of the table in ServiceNow (e.g., `incident`)
      sysId:
        title: Ticket Sys ID
        type: string
        description: Get ticket Sys ID from here - https://ibmksademo1.service-now.com/api/now/table/incident?sysparm_fields=sys_id,number
      shortDescription:
        title: New Short Description
        type: string
        description: New short description of the ticket
  steps:
  - id: modify
    name: Modify Incident in ServiceNow
    action: servicenow:now:table:modifyRecord
    input:
      tableName: ${{ parameters.tableName }}
      sysId: ${{ parameters.sysId }}
      requestBody:
        short_description: ${{ parameters.shortDescription }}
  output:
    ticketUrl: https://ibmksademo1.service-now.com/nav_to.do?uri=${{ parameters.tableName }}.do?sys_id=${{ parameters.sysId }}
    result: ${{ steps.modify.output }}


---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: servicenow-update-template
  title: ServiceNow Update Template
  description: Update details of an existing ticket in ServiceNow
  tags:
    - servicenow
    - update
spec:
  owner: "manwendra-hotmail"
  type: service
  parameters:
  - title: Provide details to update
    required:
     - tableName
     - sysId
     - shortDescription
    properties:
      tableName:
        title: Table Name
        type: string
        default: 'incident'
        description: Name of the table in ServiceNow (e.g., `incident`)
      sysId:
        title: Ticket Sys ID
        type: string
        description: Get ticket Sys ID from here - https://ibmksademo1.service-now.com/api/now/table/incident?sysparm_fields=sys_id,number
      shortDescription:
        title: New Short Description
        type: string
        description: New short description of the ticket
  steps:
  - id: update
    name: Update Incident in ServiceNow
    action: servicenow:now:table:updateRecord
    input:
      tableName: ${{ parameters.tableName }}
      sysId: ${{ parameters.sysId }}
      requestBody:
        short_description: ${{ parameters.shortDescription }}
  output:
    ticketUrl: https://ibmksademo1.service-now.com/nav_to.do?uri=${{ parameters.tableName }}.do?sys_id=${{ parameters.sysId }}
    result: ${{ steps.update.output }}


---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: servicenow-fetch-template
  title: ServiceNow Fetch Template
  description: Fetch incidents from ServiceNow
  tags:
    - servicenow
    - fetch
spec:
  owner: "manwendra-hotmail"
  type: service
  parameters:
  - title: Provide table name information
    required:
     - tableName
    properties:
      tableName:
        title: Table Name
        type: string
        default: 'incident'
        description: Name of the ServiceNow table to fetch records from (e.g., `incident`)
  steps:
  - id: fetch
    name: Fetch Incident Tickets
    action: servicenow:now:table:retrieveRecords
    input:
      tableName: ${{ parameters.tableName }}

  - id: serialize
    name: Serialize Tickets
    action: roadiehq:utils:serialize:json
    input:
      data:
        tickets: '${{ steps.fetch.output.result }}'

  - id: write
    name: Write to File
    action: roadiehq:utils:fs:write
    input:
      path: ./data.json
      content: ${{ steps.serialize.output.serialized }}

  - id: transform
    name: Transform to Text
    action: roadiehq:utils:jsonata:json:transform
    input:
      path: ${{ steps['write'].output.path }}
      expression: '{"incidents": [tickets.{"number": number, "description": short_description ,"State": incident_state, "active": active,"priority": priority,"Created By": sys_created_by,"ticket-link": "https://ibmksademo1.service-now.com/nav_to.do?uri=incident.do?sys_id="&sys_id}]}'
  output:
    text: 
      - title: Tickets
        content: | 
          'incidents:
    -
        number: INC0010003
        description: "Test Ticket for SBX Developer Hub POC"
        State: "7"
        active: "false"
        priority: "5"
        "Created By": Rakesh
        ticket-link: "https://ibmksademo1.service-now.com/nav_to.do?uri=incident.do?sys_id=c76bd30b3bd4d690f7db026aa5e45ab5"
    -
        number: INC0010014
        description: "Ticket4 - Unable to create tickets in SNOW from RHDH"
        State: "1"
        active: "true"
        priority: "5"
        "Created By": Rakesh
        ticket-link: "https://ibmksademo1.service-now.com/nav_to.do?uri=incident.do?sys_id=25b41d393b68d210f7db026aa5e45ac9"
    -
        number: INC0010015
        description: "Testing update action from RHDH"
        State: "1"
        active: "true"
        priority: "5"
        "Created By": Rakesh
        ticket-link: "https://ibmksademo1.service-now.com/nav_to.do?uri=incident.do?sys_id=7235d1f93b68d210f7db026aa5e45a4e"
    -
        number: INC0010007
        description: "I have raised this ticket by mistake, please mark it as resolved. Thanks!"
        State: "1"
        active: "true"
        priority: "5"
        "Created By": Rakesh
        ticket-link: "https://ibmksademo1.service-now.com/nav_to.do?uri=incident.do?sys_id=7f43b43933e09610be43ca989d5c7b76"
    -
        number: INC0010008
        description: "Ticket2 - Unable to create tickets in SNOW from RHDH"
        State: "1"
        active: "true"
        priority: "5"
        "Created By": Rakesh
        ticket-link: "https://ibmksademo1.service-now.com/nav_to.do?uri=incident.do?sys_id=8f76f8b53ba4d210f7db026aa5e45a8d"
    -
        number: INC0010010
        description: "Ticket3 - Unable to create tickets in SNOW from RHDH"
        State: "1"
        active: "true"
        priority: "5"
        "Created By": Rakesh
        ticket-link: "https://ibmksademo1.service-now.com/nav_to.do?uri=incident.do?sys_id=ec59f8b93ba4d210f7db026aa5e45a24"
    -
        number: INC0010011
        description: RH-Catalog
        State: "1"
        active: "true"
        priority: "5"
        "Created By": Rakesh
        ticket-link: "https://ibmksademo1.service-now.com/nav_to.do?uri=incident.do?sys_id=f22afc7d3ba4d210f7db026aa5e45aa9" ' \
          ${{ steps['transform'].output.result }}
    



